[package]
name = "dots-and-boxes"
version = "0.1.0"
edition = "2021"

[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[dependencies]
bevy = "0.13.2"
bevy_mod_picking = "0.18.2"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
